name: Documentation

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: SwiftyLab/setup-swift@v1
        with:
          swift-version: "6.3"
 
      - name: Build Documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation --target libgnss-rtcm-swift \
            --output-path ./docs \
            --transform-for-static-hosting \
            --hosting-base-path libgnss-rtcm-swift


            
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs-out

  deploy:
    name: Deploy to GitHub Pages
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
